development:
  adapter: postgresql
  encoding: unicode
  database: charity_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: charity_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: charity_production
  pool: 5
  username: postgres
  password: postgres